name: CRON Schedule job

on:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

  generate-calendar:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: go generate
        run: go generate ./gen
      - name: get diff
        run: echo "::set-output name=changed::$(git diff --name-only | wc -l)"
        id: diff
      - name: push branch
        if: ${{ steps.diff.outputs.changed != '0' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "kudagonbe"
          git config user.email "17189890+kudagonbe@users.noreply.github.com"
          git switch -c feature/update_calendar_${{ env.CURRENT_DATETIME }}
          git add .
          git commit -m "calendar update detect"
          git push -u origin feature/update_calendar_${{ env.CURRENT_DATETIME }}
      - name: create pull request
        if: ${{ steps.diff.outputs.changed != '0' }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "feature/update_calendar_${{ env.CURRENT_DATETIME }}"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update Calendar"
          pr_label: "calendar-update-detect"
        